name = "philipwalton"
compatibility_date = "2024-06-10"
pages_build_output_dir = './build'

kv_namespaces = [
  {binding = "PRIORITY_HINTS", id = "7fdf8d6f35d042a5b21b77ab6a56028e", preview_id = "40156d62dc48468aa5e21fe01ed5b01e"},
]
