name = "worker-dev"
main = "worker/index.js"
account_id = "833aa47653f1a867bf6f206ed576cd2f"

compatibility_date = "2022-09-24"
workers_dev = true

[dev]
host = "localhost:3001" # Origin server
port = 3000 # Worker server

[vars]
ENV = "development"

# Override values for `--env production` usage
[env.production]
name = "worker"
workers_dev = false
routes = [
  "philipwalton.com/",
  "philipwalton.com/shell*",
  "philipwalton.com/articles*",
  "philipwalton.com/about*",
]
[env.production.vars]
ENV = "production"
