import fs from 'fs-extra';
import * as path from 'path';

export interface Site {
  title: string;
  titleSuffix: string;
  baseUrl: string;
}

export interface Page {
  title?: string;
  path: string;
  private?: boolean;
  devOnly?: boolean;
}

export interface Article {
  title: string;
  path: string;
  date: string;
}

export interface Book {
  site: Site;
  pages: Page[];
  articles: Article[];
}

// Static site configuration
const site: Site = {
  title: 'Philip Walton',
  titleSuffix: ' — Philip Walton',
  baseUrl: 'https://philipwalton.com',
};

// Static pages configuration
const pages: Page[] = [
  {title: 'Home', path: '/'},
  {title: 'Articles', path: '/articles/'},
  {title: 'About', path: '/about/'},
];

const DIST_DIR = './dist';

/**
 * Parse articles from the Atom feed generated by Astro.
 */
async function getArticlesFromAtomFeed(): Promise<Article[]> {
  const atomPath = path.join(DIST_DIR, 'atom.xml');
  const atomXml = await fs.readFile(atomPath, 'utf-8');

  const articles: Article[] = [];
  const entryRegex = /<entry>([\s\S]*?)<\/entry>/g;

  let match;
  while ((match = entryRegex.exec(atomXml)) !== null) {
    const entry = match[1]!;

    const titleMatch = entry.match(/<title>([^<]+)<\/title>/);
    const linkMatch = entry.match(/<link href="([^"]+)"\/>/);
    const updatedMatch = entry.match(/<updated>([^<]+)<\/updated>/);

    if (titleMatch?.[1] && linkMatch?.[1] && updatedMatch?.[1]) {
      const articlePath = new URL(linkMatch[1]).pathname;

      articles.push({
        title: titleMatch[1],
        path: articlePath,
        date: updatedMatch[1],
      });
    }
  }

  // Atom feed is sorted newest first; reverse to get oldest first
  return articles.reverse();
}

export async function initBook(): Promise<Book> {
  const articles = await getArticlesFromAtomFeed();

  return {
    site,
    pages,
    articles,
  };
}
